package issue_queue_pkg;

    localparam DATA_WIDTH = 32;
    localparam IQ_SIZE = 16;
    // localparam ROB_COUNT = 32;
    localparam PRF_COUNT = 32;
    localparam INSTR_COMPRESS_WIDTH = 17;
    localparam MAX_EXEC_CYCLE = 4;
    localparam IMM_COMPRESS = 20;
    localparam FUNCT_COMB_WIDTH = 4; // representing funct3 + funct7

    // for now, have combined JAL into ALU type
    // assumes PC += imm is computed earlier
    typedef enum {ALU, LOAD, STORE, BRANCH, JALR, AUIPC} EX_MEM_TYPE;

    typedef struct packed {
        // logic instr_valid;
        logic EX_MEM_TYPE type;
        logic [FUNCT_COMB_WIDTH-1:0] funct_comb;
        // logic [INSTR_COMPRESS_WIDTH-1:0] op;
        // logic [$clog2(MAX_EXEC_CYCLE)-1:0] exec_dur; // unsure if we need to output this
        // logic imm_valid;
        // logic [IMM_COMPRESS-1:0] imm_compr;
        logic speculative;
        logic store;
        logic dest_valid;
        logic [$clog2(PRF_COUNT)-1:0] dest_ptr;
        logic src0_valid;
        logic [DATA_WIDTH-1:0] src0_data;
        logic src1_valid;
        logic [DATA_WIDTH-1:0] src1_data;
        logic [$clog2(ROB_COUNT)-1:0] rob_ptr;
    } fetch_packet_t;

// generated by ai
function automatic logic [DATAWIDTH-1:0] format_20b_to_datawidth(
    input logic [19:0] imm_20b,
    input logic [6:0]  opcode
);
    case (opcode)
        // U-Type: LUI, AUIPC
        7'b011_0111, 7'b001_0111: begin
            return DATAWIDTH'($signed({imm_20b, 12'b0}));
        end
        // J-Type: JAL
        7'b110_1111: begin
            return DATAWIDTH'($signed({imm_20b, 1'b0}));
        end
        // I, S, B, Z Types
        default: begin
            return DATAWIDTH'($signed(imm_20b));
        end
    endcase
endfunction

function automatic EX_MEM_TYPE get_ex_mem_type(
    input logic [6:0] opcode
);
    case (opcode)
        7'b011_0011: return ALU; // R-Type
        7'b001_0011: return ALU; // I-Type ALU
        7'b000_0011: return LOAD; // Load
        7'b010_0011: return STORE; // Store
        7'b110_0011: return BRANCH; // Branch
        7'b110_1111: return ALU; // JAL
        7'b110_0111: return JALR; // JALR
        7'b011_0111: return ALU; // LUI
        7'b001_0111: return AUIPC; // AUIPC
        default: return ALU; // Default to ALU for unsupported opcodes
    endcase
endfunction

function automatic logic [FUNCT_COMB_WIDTH-1:0] get_funct_comb(
    input logic [INSTR_COMPRESS_WIDTH-1:0] op
);
    logic [2:0] funct3 = op[9:7];
    logic [6:0] funct7 = op[16:10];
    return {funct7[5], funct3}; // Combine the most significant bit of funct7 with funct3
endfunction

endpackage