/*
    Since we dont use tehe valid bits in fetch_packet, look back and see if we 
    can eliminate some fields in prior stages

*/

package issue_queue_pkg;

    localparam DATA_WIDTH = 32;
    localparam IQ_SIZE = 16;
    // localparam ROB_COUNT = 32;
    localparam PRF_COUNT = 32;
    localparam INSTR_COMPRESS_WIDTH = 17;
    localparam MAX_EXEC_CYCLE = 4;
    localparam IMM_COMPRESS = 20;
    localparam FUNCT_COMB_WIDTH = 4; // representing funct3 + funct7

    // for now, have combined JAL into ALU type
    // assumes PC += imm is computed earlier
    localparam EX_MEM_TYPE_SIZE = 6;
    typedef enum logic [$clog2(EX_MEM_TYPE_SIZE)-1:0] {NOOP, ALU, MEM, BRANCH, JALR, AUIPC} EX_MEM_TYPE;

    // note: this is different form v1 b/c v1 is made for deocde_stage
    localparam MAX_EXEC_CYCLE_V2 = 2;

    typedef struct packed {
        // logic instr_valid;
        logic EX_MEM_TYPE funct_unit;
        logic [EX_MEM_TYPE_SIZE-1:0] funct_unit_one_hot;
        logic [FUNCT_COMB_WIDTH-1:0] funct_code;
        // logic [INSTR_COMPRESS_WIDTH-1:0] op;
        // logic [$clog2(MAX_EXEC_CYCLE)-1:0] exec_dur; // unsure if we need to output this
        // logic imm_valid;
        // logic [IMM_COMPRESS-1:0] imm_compr;
        logic speculative;
        logic store; // DONT NEED
        // logic dest_valid; // DONT NEED
        logic [$clog2(PRF_COUNT)-1:0] dest_ptr;
        // logic src0_valid; // DONT NEED
        logic [DATA_WIDTH-1:0] src0_data;
        // logic src1_valid; // DONT NEED
        logic [DATA_WIDTH-1:0] src1_data;
        logic [DATA_WIDTH-1:0] mem_offset_or_brnch_imm;
        logic [$clog2(ROB_COUNT)-1:0] rob_ptr;
        // additional fields
        logic [DATA_WIDTH-1:0] pc; // for branch target calculation, and for JALR and AUIPC

    } fetch_packet_t;


function automatic logic [$clog2(MAX_EXEC_CYCLE_V2)-1:0] get_exec_stage_delays_v2(
    input EX_MEM_TYPE funct_unit_type
);
    case (funct_unit_type)
        ALU: return 1;
        MEM: return 2;
        BRANCH: return 1;
        JALR: return 1;
        AUIPC: return 1;
        default:
            return 1; // Default to 1 cycle for unsupported types
    endcase
endfunction

// generated by ai
function automatic logic [DATAWIDTH-1:0] format_20b_to_datawidth(
    input logic [19:0] imm_20b,
    input logic [6:0]  opcode
);
    case (opcode)
        // U-Type: LUI, AUIPC
        7'b011_0111, 7'b001_0111: begin
            return DATAWIDTH'($signed({imm_20b, 12'b0}));
        end
        // J-Type: JAL
        7'b110_1111: begin
            return DATAWIDTH'($signed({imm_20b, 1'b0}));
        end
        // I, S, B, Z Types
        default: begin
            return DATAWIDTH'($signed(imm_20b));
        end
    endcase
endfunction

function automatic EX_MEM_TYPE get_ex_mem_type(
    input logic [6:0] opcode,
    input instr_valid
);
    if (instr_valid) begin
        case (opcode)
            7'b011_0011: return ALU; // R-Type
            7'b001_0011: return ALU; // I-Type ALU
            7'b000_0011: return MEM; // Load
            7'b010_0011: return MEM; // Store
            7'b110_0011: return BRANCH; // Branch
            // 7'b110_1111: return ALU; // JAL
            7'b110_1111: return JALR; // JAL
            7'b110_0111: return JALR; // JALR
            7'b011_0111: return ALU; // LUI
            7'b001_0111: return AUIPC; // AUIPC
            default: return ALU; // Default to ALU for unsupported opcodes
        endcase
    end else begin
        return NOOP; // If instruction is not valid, treat it as NOOP
    end
endfunction

function automatic logic [EX_MEM_TYPE_SIZE-1:0] get_ex_mem_type_one_hot(
    input logic [6:0] opcode,
    input instr_valid
);
    EX_MEM_TYPE type = get_ex_mem_type(opcode, instr_valid);
    return 1 << type; // Convert enum to one-hot encoding
endfunction

function automatic logic [FUNCT_COMB_WIDTH-1:0] get_funct_comb(
    input logic [INSTR_COMPRESS_WIDTH-1:0] op
);
    assert (FUNCT_COMB_WIDTH == 4);
    logic [6:0] opcode = op[6:0];
    EX_MEM_TYPE type = get_ex_mem_type(opcode, 1'b1);
    if (type == JALR) begin
        return op[3:0]; // 3rd bit distinguishes between JALR and JAL
    end else begin
        logic [2:0] funct3 = op[9:7];
        logic [6:0] funct7 = op[16:10];
        return {funct7[5], funct3}; // Combine the most significant bit of funct7 with funct3
    end
endfunction

endpackage