package issue_queue_pkg;

    localparam DATA_WIDTH = 32;
    localparam IQ_SIZE = 16;
    // localparam ROB_COUNT = 32;
    localparam PRF_COUNT = 32;
    localparam INSTR_COMPRESS_WIDTH = 17;
    localparam MAX_EXEC_CYCLE = 4;
    localparam IMM_COMPRESS = 20;

    typedef struct packed {
        logic instr_valid;
        logic [INSTR_COMPRESS_WIDTH-1:0] op;
        // logic [$clog2(MAX_EXEC_CYCLE)-1:0] exec_dur; // unsure if we need to output this
        // logic imm_valid;
        // logic [IMM_COMPRESS-1:0] imm_compr;
        logic speculative;
        logic store;
        logic dest_valid;
        logic [$clog2(PRF_COUNT)-1:0] dest_ptr;
        logic src0_valid;
        logic [DATA_WIDTH-1:0] src0_data;
        logic src1_valid;
        logic [DATA_WIDTH-1:0] src1_data;
    } fetch_packet_t;

// generated by ai
function automatic logic [DATAWIDTH-1:0] format_20b_to_datawidth(
    input logic [19:0] imm_20b,
    input logic [6:0]  opcode
);
    case (opcode)
        // U-Type: LUI, AUIPC
        7'b011_0111, 7'b001_0111: begin
            return DATAWIDTH'($signed({imm_20b, 12'b0}));
        end
        // J-Type: JAL
        7'b110_1111: begin
            return DATAWIDTH'($signed({imm_20b, 1'b0}));
        end
        // I, S, B, Z Types
        default: begin
            return DATAWIDTH'($signed(imm_20b));
        end
    endcase
endfunction

endpackage